# Generated by Django 6.0.5 on 2026-05-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=300)),
                ('telefono', models.CharField(max_length=20)),
                ('titulo_academico', models.CharField(max_length=200)),
                ('biografia', models.TextField()),
                ('correo', models.EmailField(max_length=254)),
                ('dedicacion', models.TextField()),
            ],
        ),
    ]
